# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-02-20 16:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DateModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(verbose_name='发布时间')),
            ],
        ),
        migrations.CreateModel(
            name='BookModel',
            fields=[
                ('datemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='homepage.DateModel')),
                ('book_title', models.CharField(max_length=20, verbose_name='标题')),
                ('book_name', models.CharField(max_length=10, verbose_name='书名')),
                ('book_auther', models.CharField(max_length=5, verbose_name='作者')),
                ('book_comment', models.TextField(verbose_name='书评')),
            ],
            options={
                'verbose_name': '书籍',
                'verbose_name_plural': '书籍',
                'db_table': 'tb_books',
            },
            bases=('homepage.datemodel', models.Model),
        ),
        migrations.CreateModel(
            name='ChatModel',
            fields=[
                ('datemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='homepage.DateModel')),
                ('chat_title', models.CharField(max_length=20, verbose_name='吐槽标签')),
                ('chat_comment', models.TextField(verbose_name='吐槽')),
            ],
            options={
                'verbose_name': '吐槽',
                'verbose_name_plural': '吐槽',
                'db_table': 'tb_chats',
            },
            bases=('homepage.datemodel', models.Model),
        ),
        migrations.CreateModel(
            name='DirayModel',
            fields=[
                ('datemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='homepage.DateModel')),
                ('diray_weather', models.CharField(max_length=10, verbose_name='天气')),
                ('diray_date', models.DateField(verbose_name='日期')),
                ('diray_comment', models.TextField(verbose_name='日记正文')),
            ],
            options={
                'verbose_name': '日记',
                'verbose_name_plural': '日记',
                'db_table': 'tb_dirays',
            },
            bases=('homepage.datemodel', models.Model),
        ),
        migrations.CreateModel(
            name='MovieModel',
            fields=[
                ('datemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='homepage.DateModel')),
                ('movie_title', models.CharField(max_length=20, verbose_name='标题')),
                ('movie_name', models.CharField(max_length=10, verbose_name='电影名称')),
                ('movie_comment', models.TextField(verbose_name='影评')),
            ],
            options={
                'verbose_name': '电影',
                'verbose_name_plural': '电影',
                'db_table': 'tb_movies',
            },
            bases=('homepage.datemodel', models.Model),
        ),
        migrations.CreateModel(
            name='MusicModel',
            fields=[
                ('datemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='homepage.DateModel')),
                ('music_name', models.CharField(max_length=10, verbose_name='音乐名')),
                ('music_singer', models.CharField(max_length=5, verbose_name='歌手')),
                ('music_comment', models.TextField(verbose_name='音乐评论')),
            ],
            options={
                'verbose_name': '音乐',
                'verbose_name_plural': '音乐',
                'db_table': 'tb_musics',
            },
            bases=('homepage.datemodel', models.Model),
        ),
    ]
