# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-02-20 17:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendModel',
            fields=[
                ('datemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='homepage.DateModel')),
                ('friend_name', models.CharField(max_length=10, verbose_name='昵称')),
                ('friend_email', models.CharField(max_length=20, verbose_name='邮箱')),
                ('friend_wechat', models.CharField(max_length=20, verbose_name='微信')),
                ('friend_comment', models.TextField(verbose_name='留言')),
            ],
            options={
                'verbose_name': '朋友',
                'verbose_name_plural': '朋友',
                'db_table': 'tb_friends',
            },
            bases=('homepage.datemodel', models.Model),
        ),
    ]
