# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-02-21 11:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_friendmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='datemodel',
            name='img',
            field=models.ImageField(default='img/logo.png', upload_to='img/', verbose_name='配图'),
            preserve_default=False,
        ),
    ]
