# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-02-21 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_datemodel_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datemodel',
            name='img',
        ),
        migrations.AddField(
            model_name='bookmodel',
            name='book_img',
            field=models.ImageField(default='img/logo.png', upload_to='img', verbose_name='图书配图'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chatmodel',
            name='chat_img',
            field=models.ImageField(default='img/logo.png', upload_to='img', verbose_name='吐槽配图'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diraymodel',
            name='diray_img',
            field=models.ImageField(default='img/logo.png', upload_to='img', verbose_name='日记配图'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='moviemodel',
            name='movie_img',
            field=models.ImageField(default='img/logo.png', upload_to='img', verbose_name='电影配图'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='musicmodel',
            name='music_img',
            field=models.ImageField(default='img/logo.png', upload_to='img', verbose_name='音乐配图'),
            preserve_default=False,
        ),
    ]
