# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-02-22 06:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_auto_20190221_1927'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallModel',
            fields=[
                ('datemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='homepage.DateModel')),
                ('call_title', models.CharField(max_length=30, verbose_name='公告标题')),
                ('call_comment', models.TextField(verbose_name='公告内容')),
            ],
            options={
                'verbose_name': '公告',
                'verbose_name_plural': '公告',
                'db_table': 'tb_call',
            },
            bases=('homepage.datemodel', models.Model),
        ),
    ]
